<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\YuckQi.Data.Sql.EntityFramework\YuckQi.Data.Sql.EntityFramework.csproj" />
  </ItemGroup>

</Project>
