<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\YuckQi.Data.DocumentDb.DynamoDb\YuckQi.Data.DocumentDb.DynamoDb.csproj" />
    <ProjectReference Include="..\..\src\YuckQi.Data\YuckQi.Data.csproj" />
  </ItemGroup>

</Project>
